name: Test Suite

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Checkout Code
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Establish Docker Cache
        uses: actions/cache@v3
        id: docker-cache
        with:
          path: docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Load cached Docker layers
        run: |
          if [ -d "docker-cache" ]; then
            cat docker-cache/x* > my-image.tar
            docker load < my-image.tar
            rm -rf docker-cache
          fi

      # - name: Setup Build Tooling
      #   id: setup
      #   run: |
      #     base=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/author/dev-base/tags?page_size=1'|jq '."results"[]["name"]')
      #     base=$(sed -e 's/^"//' -e 's/"$//' <<<"$base")
      #     echo Retrieving author/dev/dev-base:$base
      #     docker pull author/dev-base:$base

      #     deno=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/author/dev-deno/tags?page_size=1'|jq '."results"[]["name"]')
      #     deno=$(sed -e 's/^"//' -e 's/"$//' <<<"$deno")
      #     echo Retrieving author/dev/dev-deno:$deno
      #     docker pull author/dev-deno:$deno

      #     browser=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/author/dev-browser/tags?page_size=1'|jq '."results"[]["name"]')
      #     browser=$(sed -e 's/^"//' -e 's/"$//' <<<"$browser")
      #     echo Retrieving author/dev/dev-browser:$browser
      #     docker pull author/dev-browser:$browser

      #     node=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/author/dev-node/tags?page_size=1'|jq '."results"[]["name"]')
      #     node=$(sed -e 's/^"//' -e 's/"$//' <<<"$node")
      #     echo Retrieving author/dev/dev-node:$node
      #     docker pull author/dev-node:$node

      #     # node -e "const p=new Set(Object.keys(require('./package.json').peerDependencies));p.delete('@author.io/dev');console.log('npm i ' + Array.from(p).join(' '))"
      #     version=$(npm show @author.io/dev version)
      #     echo $version
      #     npm i -g @author.io/dev@$version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Test
      #   if: success()
      #   run: |
      #     dev -v
      #     npm run ci

      - name: Build & Test
        if: success()
        run: |
          npm test

      - name: Tag
        id: autotagger
        if: success()
        uses: butlerlogic/action-autotag@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

        # If the new version/tag is a pre-release (i.e. 1.0.0-beta.1), create
        # an environment variable indicating it is a prerelease.
      - name: Pre-release
        if: steps.autotagger.outputs.tagname != ''
        run: |
          if [[ "${{ steps.autotagger.output.version }}" == *"-"* ]]; then echo "::set-env IS_PRERELEASE=true";else echo "::set-env IS_PRERELEASE=''";fi

      - name: Release
        id: create_release
        if: steps.autotagger.outputs.tagname != ''
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.autotagger.outputs.tagname }}
          release_name: ${{ steps.autotagger.outputs.tagname }}
          body: ${{ steps.autotagger.outputs.tagmessage }}
          draft: false
          prerelease: env.IS_PRERELEASE != ''

        # Build tarballs of the module code.
      - name: Build Release Artifacts
        id: build_release
        if: steps.create_release.outputs.id != ''
        run: |
          cp -rf .dist ./dist

        # Upload tarballs to the release.
      - name: Upload Release Artifacts
        uses: AButler/upload-release-assets@v2.0
        if: steps.create_release.outputs.id != ''
        with:
          files: '.dist/*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.autotagger.outputs.tagname }}

      - name: Publish to npm
        id: publish_npm
        if: steps.autotagger.outputs.tagname != ''
        uses: author/action-publish@master
        with:
          scan: ./dist
          prerelease-dist-tag: next
        env:
          REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

      - name: Rollback Release
        if: failure() && steps.create_release.outputs.id != ''
        uses: author/action-rollback@stable
        with:
          tag: ${{ steps.autotagger.outputs.tagname }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
